data_source music:
  type: bigquery
  connection:
    account_info_json_path: /usr/local/airflow/include/gcp/de-creds.json
    auth_scopes:
    - https://www.googleapis.com/auth/bigquery
    - https://www.googleapis.com/auth/cloud-platform
    - https://www.googleapis.com/auth/drive
    project_id: 'de-project-2025-455709'
    dataset: music

# For soda cloud Integration, remove comments and add your creds (Optional)
# soda_cloud:
#   host: cloud.soda.io
#   api_key_id: ${SODA_API_KEY_ID} #Or put your soda api key id
#   api_key_secret: ${SODA_API_KEY_SECRET} #Or put your soda api key secret